import Head from "next/head";
import Presentation from "@/components/Presentation";
import About from "@/components/About";
import Works from "@/components/Works";
import Services from "@/components/Services";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Presentation */}
      <section id="home">
        <Presentation />
      </section>

      {/* About */}
      <section id="about">
        <About />
      </section>

      {/* Works */}
      <section id="works">
        <Works />
      </section>

      {/* Services */}
      <section id="services">
        <Services />
      </section>

      {/* Contact */}
      <section id="contact">
        <Contact />
      </section>
    </>
  );
}
